

export const FETCH_PLACEORDER_REQUEST='FETCH_PLACEORDER_REQUEST';
export const FETCH_PLACEORDER_SUCESS='FETCH_PLACEORDER_SUCESS';
export const FETCH_PLACEORDER_FAILURE='FETCH_PLACEORDER_FAILURE';

export const FETCH_PLACEORDERALL_REQUEST='FETCH_PLACEORDERALL_REQUEST';
export const FETCH_PLACEORDERALL_SUCESS='FETCH_PLACEORDERALL_SUCESS';
export const FETCH_PLACEORDERALL_FAILURE='FETCH_PLACEORDERALL_FAILURE';