export const FETCH_MENUCATEGORY_REQUEST='FETCH_MENUCATEGORY_REQUEST';
export const FETCH_MENUCATEGORY_SUCESS='FETCH_MENUCATEGORY_SUCESS';
export const FETCH_MENUCATEGORY_FAILURE='FETCH_MENUCATEGORY_FAILURE';

export const FETCH_MAINDISH_REQUEST='FETCH_MAINDISH_REQUEST';
export const FETCH_MAINDISH_SUCESS='FETCH_MAINDISH_SUCESS';
export const FETCH_MAINDISH_FAILURE='FETCH_MAINDISH_FAILURE';