export const FETCH_STARTERS_REQUEST='FETCH_STARTERS_REQUEST';
export const FETCH_STARTERS_SUCESS='FETCH_STARTERS_SUCESS';
export const FETCH_STARTERS_FAILURE='FETCH_STARTERS_FAILURE';

export const FETCH_MAINDISH_REQUEST='FETCH_MAINDISH_REQUEST';
export const FETCH_MAINDISH_SUCESS='FETCH_MAINDISH_SUCESS';
export const FETCH_MAINDISH_FAILURE='FETCH_MAINDISH_FAILURE';